CREATE DATABASE SUSHI;
USE SUSHI;

 -- CRIANDO TABELAS
 -- TB_USUARIO
 CREATE TABLE TB_USUARIO(
 ID_USUARIO INT NOT NULL AUTO_INCREMENT
 , NM_LOGIN VARCHAR(20) NOT NULL
 , CD_SENHA VARCHAR(20) NOT NULL
 ,NM_USUARIO VARCHAR(50) NOT NULL
 ,CD_ATIVO ENUM ('A','I') DEFAULT 'A'
  ,DT_CRIACAO DATETIME default current_timestamp
 ,CONSTRAINT PK_USUARIO PRIMARY KEY (ID_USUARIO)
 );
 
 DESC TB_USUARIO;
 -- inserindo dois usuários como teste
 INSERT INTO TB_USUARIO (NM_LOGIN, CD_SENHA, NM_USUARIO)
  VALUES ('lRamos','password','Lazaro Ramos');
  
   INSERT INTO TB_USUARIO (NM_LOGIN, CD_SENHA, NM_USUARIO)
  VALUES ('jGomes','password','Juliana Gomes');

select * from TB_USUARIO;

-- TB_CARDAPIO
CREATE TABLE TB_ITEM(
 ID_ITEM INT NOT NULL AUTO_INCREMENT
 ,INDICE_ITEM INT UNIQUE
 ,NM_ITEM VARCHAR(50) NOT NULL
 ,DS_ITEM VARCHAR(200) NOT NULL
 ,VL_ITEM DECIMAL (5,2) NOT NULL
 ,CONSTRAINT PK_ITEM PRIMARY KEY (ID_ITEM)
);

DESC tb_item;
-- INSERINDO VALORES DE TESTE
INSERT INTO TB_ITEM (INDICE_ITEM, NM_ITEM, DS_ITEM, VL_ITEM) VALUES
(1,'GOHAN','BOLINHO DE ARROZ TRADICIONAL',4.50),
(2,'HOT ROLL','Sushi empanado e frito, o hot roll é um prato consumido quente',10.00),
(3,'GUIOZA','Pasteizinhos',3.00);

SELECT * FROM TB_ITEM;

--  BAIRRO
CREATE TABLE TB_BAIRRO
(
	ID_BAIRRO INT NOT NULL AUTO_INCREMENT
    ,NM_BAIRRO VARCHAR (30) NOT NULL
    ,VL_DELIVERY DECIMAL (4,2) NOT NULL
    ,CD_APROVACAO ENUM ('0','1') DEFAULT '1'
    ,NM_CIDADE VARCHAR(15) DEFAULT 'PRAIA GRANDE'
    ,CONSTRAINT PK_BAIRRO PRIMARY KEY(ID_BAIRRO)
);

DESC TB_BAIRRO;
-- INSERINDO VALORES PARA TESTE
INSERT INTO TB_BAIRRO (NM_BAIRRO, VL_DELIVERY)
VALUES ('Mirim',2.00), ('Anhanguera',2.50), ('Samambaia',4.00);
-- aceitam delivery
-- alterando o campo vl_delivery para aceitar NULL quando não entregar no bairro
ALTER TABLE TB_BAIRRO CHANGE COLUMN VL_DELIVERY  VL_DELIVERY DECIMAL (4,2) NULL;
INSERT INTO TB_BAIRRO (NM_BAIRRO, VL_DELIVERY,CD_APROVACAO)
VALUES ('Real',NULL,'0'), ('Solemar',NULL,'0'), ('Princesa',NULL,'0');

select * from tb_bairro;

-- CLIENTE
CREATE TABLE TB_CLIENTE(
	ID_CLIENTE INT NOT NULL AUTO_INCREMENT
    ,NM_CLIENTE VARCHAR(50) NOT NULL
    ,CD_TEL1 VARCHAR(15) NOT NULL
    ,CD_TEL2 VARCHAR(15) NULL DEFAULT 'NÃO INFORMADO'
    ,CD_CEP CHAR(8) NULL DEFAULT '-'
    ,NM_RUA VARCHAR(30) NULL DEFAULT 'NÃO INFORMADO'
    ,DS_COMPLEMENTO VARCHAR(30) NULL DEFAULT 'NÃO INFORMADO'
    ,DS_REFERENCIA VARCHAR(50) NULL DEFAULT '-'
    ,FK_CD_BAIRRO INT NOT NULL
    ,CONSTRAINT PK_CLIENTE PRIMARY KEY (ID_CLIENTE)
    ,CONSTRAINT FK_BAIRRO FOREIGN KEY(FK_CD_BAIRRO) REFERENCES TB_BAIRRO  (ID_BAIRRO)
);

DESC TB_CLIENTE;
-- INSERINDO PARA TESTE
INSERT INTO TB_CLIENTE (NM_CLIENTE,CD_TEL1,FK_CD_BAIRRO) VALUES  ('Jonathan','13991239808',3),('Patricia','13998239809',5);
-- inserção testando valores nulos e padrões acima
INSERT INTO TB_CLIENTE VALUES
(DEFAULT,'Amanda','98813911','98813911', '11712000','Av Melvi Principal','nº 411 - Sobrado de cima','Em frente bar do Zé', 2),
(DEFAULT,'Douglas','1398813901','-', '11712620','R. Eucalíptos','N° 128 Casa','-', 3),
(DEFAULT,'Sérgio','1399999999','1399999999', '11712620','R. Eucalíptos','N° 119 Casa','-', 3),
(DEFAULT,'Francisco','1398888888','1199999999', '11700600','R. Bahia','N° 1194 Casa','Rua lateral Casas Bahia', 4);

SELECT * FROM tb_cliente;
-- vamos testar o JOIN entre o bairro e o cliente para saber o bairro de cada cliente
-- VAMOS FAZER UMA VIEW PARA FACILITAR
CREATE VIEW VW_DETALHE_CLIENTE AS
	SELECT C.ID_CLIENTE ,C.NM_CLIENTE, C.CD_TEL1, C.CD_CEP, C.NM_RUA, C.DS_COMPLEMENTO, C.DS_REFERENCIA,
	B.NM_BAIRRO, B.VL_DELIVERY, B.CD_APROVACAO 
	FROM TB_CLIENTE as C  JOIN TB_BAIRRO as B
	ON C.FK_CD_BAIRRO =  B.ID_BAIRRO;